services:
    sonata.admin.livebroadcast:
        class: Martin1982\LiveBroadcastBundle\Admin\LiveBroadcastAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Live"
              label: "Live Broadcasts"
        arguments:
            - ~
            - Martin1982\LiveBroadcastBundle\Entity\LiveBroadcast
            - ~
        calls:
            - [ setTranslationDomain, [LiveBroadcastBundle]]

    sonata.admin.channel:
        class: Martin1982\LiveBroadcastBundle\Admin\ChannelAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Live"
              label: "Channels"
        arguments:
            - ~
            - Martin1982\LiveBroadcastBundle\Entity\Channel\BaseChannel
            - ~
        calls:
            - [setSubClasses, [ { "Twitch Channel": Martin1982\LiveBroadcastBundle\Entity\Channel\ChannelTwitch } ] ] # @TODO Add later; , "Facebook Channel": Martin1982\LiveBroadcastBundle\Entity\Channel\ChannelFacebook

    sonata.admin.streaminput:
            class: Martin1982\LiveBroadcastBundle\Admin\InputAdmin
            tags:
                - name: sonata.admin
                  manager_type: orm
                  group: "Live"
                  label: "Inputs"
            arguments:
                - ~
                - Martin1982\LiveBroadcastBundle\Entity\Input\BaseInput
                - ~
            calls:
                - [setSubClasses, [ { "File Input": Martin1982\LiveBroadcastBundle\Entity\Input\InputFile } ] ] # @TODO Add later; , "URL Input": Martin1982\LiveBroadcastBundle\Entity\Input\InputUrl
