services:
    sonata.admin.livebroadcast:
        class: Martin1982\LiveBroadcastBundle\Admin\LiveBroadcastAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Live"
              label: "Live Broadcasts"
        arguments:
            - ~
            - Martin1982\LiveBroadcastBundle\Entity\LiveBroadcast
            - ~
        calls:
            - [ setTranslationDomain, [LiveBroadcastBundle]]

    sonata.admin.channel:
        class: Martin1982\LiveBroadcastBundle\Admin\ChannelAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Live"
              label: "Channels"
        arguments:
            - ~
            - Martin1982\LiveBroadcastBundle\Entity\Channel\BaseChannel
            - ~
        calls:
            - [setSubClasses, [ { ChannelTwitch: Martin1982\LiveBroadcastBundle\Entity\Channel\ChannelTwitch } ] ]

    sonata.admin.streaminput:
            class: Martin1982\LiveBroadcastBundle\Admin\InputAdmin
            tags:
                - name: sonata.admin
                  manager_type: orm
                  group: "Live"
                  label: "Inputs"
            arguments:
                - ~
                - Martin1982\LiveBroadcastBundle\Entity\Input\BaseInput
                - ~
            calls:
                - [setSubClasses, [ { InputFile: Martin1982\LiveBroadcastBundle\Entity\Input\InputFile }, { InputUrl: Martin1982\LiveBroadcastBundle\Entity\Input\InputUrl } ] ]
