imports:
  - { resource: 'services-input.yml' }
  - { resource: 'services-output.yml' }

services:
  live.broadcast.command.broadcast:
    class: Martin1982\LiveBroadcastBundle\Command\BroadcasterCommand
    arguments:
        - "@live.broadcast.scheduler"
        - "@logger"
        - "%livebroadcast.eventloop.timer%"
    tags:
        - { name: 'console.command' }

  live.broadcast.command.shelltest:
    class: Martin1982\LiveBroadcastBundle\Command\ShellTestCommand
    tags:
        - { name: 'console.command' }

  live.broadcast.scheduler.commands:
      class: Martin1982\LiveBroadcastBundle\Broadcaster\AbstractSchedulerCommands
      factory: [Martin1982\LiveBroadcastBundle\Broadcaster\SchedulerCommandsDetector, createSchedulerCommands]
      arguments:
          - "%kernel.root_dir%"
          - "%kernel.environment%"
          - "%livebroadcast.ffmpeg.logdirectory%"

  live.broadcast.starter:
      class: Martin1982\LiveBroadcastBundle\Service\BroadcastStarter
      arguments:
          - "@live.broadcast.streaminput.service"
          - "@live.broadcast.streamoutput.service"
          - "@live.broadcast.scheduler.commands"

  live.broadcast.broadcastmanager:
      class: Martin1982\LiveBroadcastBundle\Service\BroadcastManager
      arguments:
          - "@doctrine.orm.entity_manager"
          - "@live.broadcast.channelapi.stack"

  live.broadcast.channel_validator:
      class: Martin1982\LiveBroadcastBundle\Service\ChannelValidatorService
      arguments:
        - "@kernel"
        - "@doctrine.orm.entity_manager"
        - "@validator"

  live.broadcast.scheduler:
      class: Martin1982\LiveBroadcastBundle\Broadcaster\Scheduler
      arguments:
        - "@live.broadcast.channel_validator"
        - "@live.broadcast.starter"
        - "@live.broadcast.broadcastmanager"
        - "@live.broadcast.scheduler.commands"
        - "@logger"
      tags: [{ name: monolog.logger, channel: livebroadcaster }]

  live.broadcast.thumbnail.uploader:
      class: Martin1982\LiveBroadcastBundle\Service\ThumbnailUploadService
      arguments:
          - '%livebroadcast.thumbnail.uploaddirectory%'

  live.broadcast.thumbnail.listener:
      class: Martin1982\LiveBroadcastBundle\EventListener\ThumbnailUploadListener
      arguments:
          - '@live.broadcast.thumbnail.uploader'
      tags:
          - { name: doctrine.event_listener, event: prePersist }
          - { name: doctrine.event_listener, event: preUpdate }
          - { name: doctrine.event_listener, event: postLoad }

# Remote API stack
  live.broadcast.channelapi.stack:
      class: Martin1982\LiveBroadcastBundle\Service\ChannelApi\ChannelApiStack

# Facebook
  live.broadcast.facebookapi.service:
      class: Martin1982\LiveBroadcastBundle\Service\ChannelApi\FacebookApiService
      public: true
      arguments:
          - "@doctrine.orm.entity_manager"
          - "%livebroadcast.fb.appid%"
          - "%livebroadcast.fb.appsecret%"
      tags:
          - { name: live.broadcast.api }

# Youtube
  live.broadcast.googleredirect.service:
      class: Martin1982\LiveBroadcastBundle\Service\GoogleRedirectService
      arguments:
          - "@router"
          - "%livebroadcast.yt.redirectroute%"
  live.broadcast.channelapi.client.config.google:
      class: Martin1982\LiveBroadcastBundle\Service\ChannelApi\Client\Config\GoogleConfig
      arguments:
          - "%livebroadcast.yt.clientid%"
          - "%livebroadcast.yt.clientsecret%"
  live.broadcast.channelapi.client.config.youtube:
      class: Martin1982\LiveBroadcastBundle\Service\ChannelApi\Client\Config\YouTubeConfig
      arguments:
          - "%router.request_context.scheme%://%router.request_context.host%"
          - "%livebroadcast.thumbnail.web_path%"
  live.broadcast.channelapi.client.google:
      public: true
      class: Martin1982\LiveBroadcastBundle\Service\ChannelApi\Client\GoogleClient
      arguments:
          - "@live.broadcast.channelapi.client.config.google"
          - "@live.broadcast.googleredirect.service"
          - "@logger"
  live.broadcast.channelapi.client.youtube:
      public: true
      class: Martin1982\LiveBroadcastBundle\Service\ChannelApi\Client\YouTubeClient
      arguments:
          - "@live.broadcast.channelapi.client.config.youtube"
          - "@live.broadcast.channelapi.client.google"
  live.broadcast.youtubeapi.service:
      class: Martin1982\LiveBroadcastBundle\Service\ChannelApi\YouTubeApiService
      public: true
      arguments:
          - "@doctrine.orm.entity_manager"
          - "@logger"
          - "@live.broadcast.channelapi.client.youtube"
      tags:
          - { name: live.broadcast.api }
          - { name: monolog.logger, channel: livebroadcaster }
