services:
  live.broadcast.scheduler.commands:
    class: Martin1982\LiveBroadcastBundle\Broadcaster\SchedulerCommands
    arguments:
      - "%kernel.environment%"
  live.broadcast.scheduler:
    class: Martin1982\LiveBroadcastBundle\Broadcaster\Scheduler
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@live.broadcast.scheduler.commands"
