services:
  live.broadcast.command.broadcast:
    class: Martin1982\LiveBroadcastBundle\Command\BroadcasterCommand
    arguments: ["@live.broadcast.scheduler", "%livebroadcast.eventloop.enabled%", "%livebroadcast.eventloop.timer%"]
    tags:
        - { name: 'console.command' }

  live.broadcast.command.broadcastend:
    class: Martin1982\LiveBroadcastBundle\Command\BroadcastEndCommand
    arguments: ["@live.broadcast.broadcastmanager"]
    tags:
        - { name: 'console.command' }

  live.broadcast.command.shelltest:
    class: Martin1982\LiveBroadcastBundle\Command\ShellTestCommand
    tags:
        - { name: 'console.command' }

  live.broadcast.scheduler.commands:
      class: Martin1982\LiveBroadcastBundle\Broadcaster\AbstractSchedulerCommands
      factory: [Martin1982\LiveBroadcastBundle\Broadcaster\SchedulerCommandsDetector, createSchedulerCommands]
      arguments:
          - "%kernel.root_dir%"
          - "%kernel.environment%"
          - "%livebroadcast.ffmpeg.logdirectory%"

  live.broadcast.broadcastmanager:
      class: Martin1982\LiveBroadcastBundle\Service\BroadcastManager
      arguments: ["@doctrine.orm.entity_manager", "@live.broadcast.streammanager"]

  live.broadcast.streammanager:
      class: Martin1982\LiveBroadcastBundle\Service\StreamManager
      arguments: ["@event_dispatcher", "@live.broadcast.scheduler.commands"]

  live.broadcast.scheduler:
      class: Martin1982\LiveBroadcastBundle\Broadcaster\Scheduler
      arguments:
          - "@doctrine.orm.entity_manager"
          - "@live.broadcast.scheduler.commands"
          - "@live.broadcast.streamoutput.service"
          - "@live.broadcast.streaminput.service"
          - "@event_dispatcher"
          - "@logger"
      tags: [{ name: monolog.logger, channel: livebroadcaster }]

  live.broadcast.thumbnail.uploader:
      class: Martin1982\LiveBroadcastBundle\Service\ThumbnailUploadService
      arguments: ['%livebroadcast.thumbnail.uploaddirectory%']

  live.broadcast.thumbnail.listener:
      class: Martin1982\LiveBroadcastBundle\EventListener\ThumbnailUploadListener
      arguments: ['@live.broadcast.thumbnail.uploader']
      tags:
          - { name: doctrine.event_listener, event: prePersist }
          - { name: doctrine.event_listener, event: preUpdate }
          - { name: doctrine.event_listener, event: postLoad }

  live.broadcast.facebook_pre_broadcast_listener:
      class: Martin1982\LiveBroadcastBundle\EventListener\FacebookPreBroadcastListener
      arguments: ["@live.broadcast.facebookapi.service"]
      tags:
          - { name: kernel.event_subscriber }
  live.broadcast.youtube_pre_broadcast_listener:
      class: Martin1982\LiveBroadcastBundle\EventListener\YouTubePreBroadcastListener
      arguments: ["@live.broadcast.youtubeapi.service", "@live.broadcast.googleredirect.service"]
      tags:
          - { name: kernel.event_subscriber }
  live.broadcast.youtube_post_broadcast_listener:
      class: Martin1982\LiveBroadcastBundle\EventListener\YouTubePostBroadcastListener
      arguments: ["@live.broadcast.youtubeapi.service", "@live.broadcast.googleredirect.service"]
      tags:
          - { name: kernel.event_subscriber }
  live.broadcast.youtube_post_broadcastloop_listener:
      class: Martin1982\LiveBroadcastBundle\EventListener\YouTubePostBroadcastLoopListener
      arguments: ["@doctrine.orm.entity_manager", "@live.broadcast.scheduler.commands", "@live.broadcast.youtubeapi.service", "@kernel", "@live.broadcast.googleredirect.service", "@logger"]
      tags:
          - { name: kernel.event_subscriber }
          - { name: monolog.logger, channel: livebroadcaster }
  live.broadcast.youtube_switch_monitor_listener:
      class: Martin1982\LiveBroadcastBundle\EventListener\YouTubeSwitchMonitorListener
      arguments: ["@live.broadcast.scheduler.commands", "@live.broadcast.streamoutput.service", "@live.broadcast.streaminput.service", "@live.broadcast.youtubeapi.service", "@live.broadcast.googleredirect.service", "@logger"]
      tags:
          - { name: kernel.event_subscriber }
          - { name: monolog.logger, channel: livebroadcaster }

  live.broadcast.streaminput.service:
      class: Martin1982\LiveBroadcastBundle\Service\StreamInputService

  live.broadcast.input.file:
      class: Martin1982\LiveBroadcastBundle\Service\StreamInput\InputFile
      tags:
          - { name: live.broadcast.input, inputtype: 'File' }
  live.broadcast.input.url:
      class: Martin1982\LiveBroadcastBundle\Service\StreamInput\InputUrl
      tags:
          - { name: live.broadcast.input, inputtype: 'Url' }
  live.broadcast.input.rtmp:
      class: Martin1982\LiveBroadcastBundle\Service\StreamInput\InputRtmp
      tags:
          - { name: live.broadcast.input, inputtype: 'Rtmp' }
  live.broadcast.input.monitor:
      class: Martin1982\LiveBroadcastBundle\Service\StreamInput\InputMonitorStream
      tags:
          - { name: live.broadcast.input, inputtype: 'Monitor' }

  live.broadcast.streamoutput.service:
      class: Martin1982\LiveBroadcastBundle\Service\StreamOutputService

  live.broadcast.output.youtube:
      class: Martin1982\LiveBroadcastBundle\Service\StreamOutput\OutputYouTube
      tags:
          - { name: live.broadcast.output, platform: 'YouTube' }
  live.broadcast.output.facebook:
      class: Martin1982\LiveBroadcastBundle\Service\StreamOutput\OutputFacebook
      tags:
          - { name: live.broadcast.output, platform: 'Facebook' }
  live.broadcast.output.twitch:
      class: Martin1982\LiveBroadcastBundle\Service\StreamOutput\OutputTwitch
      tags:
          - { name: live.broadcast.output, platform: 'Twitch' }
  live.broadcast.output.ustream:
      class: Martin1982\LiveBroadcastBundle\Service\StreamOutput\OutputUstream
      tags:
          - { name: live.broadcast.output, platform: 'Ustream' }
  live.broadcast.output.lively:
      class: Martin1982\LiveBroadcastBundle\Service\StreamOutput\OutputLively
      tags:
          - { name: live.broadcast.output, platform: 'Live.ly' }

  live.broadcast.channelapi.stack:
      class: Martin1982\LiveBroadcastBundle\Service\ChannelApi\ChannelApiStack
  live.broadcast.googleredirect.service:
      class: Martin1982\LiveBroadcastBundle\Service\GoogleRedirectService
      arguments: ["@router", "%livebroadcast.yt.redirectroute%"]
  live.broadcast.facebookapi.service:
      class: Martin1982\LiveBroadcastBundle\Service\ChannelApi\FacebookApiService
      arguments: ["%livebroadcast.fb.appid%", "%livebroadcast.fb.appsecret%"]
      tags:
          - { name: live.broadcast.api }
  live.broadcast.youtubeapi.service:
      class: Martin1982\LiveBroadcastBundle\Service\ChannelApi\YouTubeApiService
      arguments: ["%livebroadcast.yt.clientid%", "%livebroadcast.yt.clientsecret%", "%router.request_context.scheme%://%router.request_context.host%", "%livebroadcast.thumbnail.web_path%", "@doctrine.orm.entity_manager", "@logger", "@live.broadcast.googleredirect.service"]
      tags:
          - { name: live.broadcast.api }
          - { name: monolog.logger, channel: livebroadcaster }
